### ISSUE TITLE
TypeError: Generator is already running

### ISSUE THREAD

**Issue by fiatjaf** [alidavut/locus#11]
I get this whenever I try to type anything after the REPL is shown. Not in all places of the script, but in many. I don't know why, perhaps because I'm calling it inside callback functions or some other async magic?

Here's an example:

```
 /home/fiatjaf/comp/wft/trelew/index.js - Line: 194 
————————————————————————————————————————————————————
186 : 
187 :     // list comments
188 :     var comments = vorpal.find('comments')
189 :     if (comments) comments.remove()
190 :     vorpal
191 :       .command('comments', "list this card's comments.")
192 :       .alias('ls comments')
193 :       .action(function (_, cb) {
ʆ: readline.js:924
            throw err;
            ^

TypeError: Generator is already running
    at next (native)
    at ReadStream.onData (readline.js:918:36)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at TTY.onread (net.js:523:20)
    at Function.module.exports.loopWhile (/home/fiatjaf/comp/wft/trelew/node_modules/deasync/index.js:64:21)
    at CommandInstance.listener (eval at <anonymous> (/home/fiatjaf/comp/wft/trelew/index.js:195:14), <anonymous>:95:11)
    at eval (eval at <anonymous> (/home/fiatjaf/comp/wft/trelew/index.js:195:14), <anonymous>:96:4)
fiatjaf@spooner ~/c/w/trelew> 
```

**Comment by alidavut** [comment]
I cannot reoccur the issue

**Comment by fiatjaf** [comment]
I'll try again in another computer and another program then come back with a reproducible case if the problem persists.
